### ISSUE TITLE
Textures distorted on MacOS

### ISSUE THREAD

**Issue by kdaker** [sangwe11/OpenGL-SDL2-and-Assimp#1]
I tried running this project on a mac, unfortunately the textures are not displaying properly, see attached files.

Any ideas what could be wrong?

![screen shot 2017-10-07 at 9 16 28 pm](https://user-images.githubusercontent.com/905997/31313873-3b4ef550-aba5-11e7-8396-f6a2151f0264.png)
![screen shot 2017-10-07 at 9 17 23 pm](https://user-images.githubusercontent.com/905997/31313872-3b475886-aba5-11e7-9d3e-0836e1867ef5.png)

**Comment by sangwe11** [comment]
It looks like an issue with the ordering of attribute locations specific to MacOS. Unfortunately I do not have access to a device to test for a fix, however updating the code and shaders to make use of layout qualifiers should resolve the issue.
